import type { Metadata } from 'next'
import { Funnel_Display, Lexend } from 'next/font/google'
import './globals.css'

const funnelDisplay = Funnel_Display({
  variable: '--font-funnel-display',
  subsets: ['latin'],
})

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${lexend.className} ${funnelDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
